const ARTICLES = [
  { file: "The Craftsman 01 primes.md", title: "The Craftsman: One." },
  { file: "The Craftsman 02 primes.md", title: "The Craftsman: Two." },
  { file: "The Craftsman 03 primes.md", title: "The Craftsman: Three." },
  { file: "The Craftsman 04 Prime Factorizer.md", title: "The Craftsman: 4" },
  { file: "The Craftsman 05 Prime Factorizer.md", title: "The Craftsman: 5" },
  { file: "The Craftsman 06 Socket Service 1.md", title: "The Craftsman: 6 SocketService 1" },
  { file: "The Craftsman 07 Socket Service 2.md", title: "The Craftsman: 7 SocketService 2" },
  { file: "The Craftsman 08 Socket Service 3.md", title: "The Craftsman: 8 SocketService 3" },
  { file: "The Craftsman 09 Socket Service 4.md", title: "The Craftsman: 9 SocketService 4" },
  { file: "The Craftsman 10 Socket Service 5.md", title: "The Craftsman: 10 SocketService 5 Dangling Threads" },
  { file: "The Craftsman 11 SMCRemote Part I.md", title: "The Craftsman: 11 SMCRemote Part I What's main got to do with it?" },
  { file: "The Craftsman 12 SMCRemote Part II.md", title: "The Craftsman: 12 SMCRemote Part II Three Ugly Lines" },
  { file: "The Craftsman 13 SMCRemote Part III.md", title: "The Craftsman: 13 SMCRemote Part III Objects" },
  { file: "The Craftsman 14 SMCRemote Part IV.md", title: "The Craftsman: 14 SMCRemote Part IV Transactions" },
  { file: "The Craftsman 15 SMCRemote Part V.md", title: "The Craftsman: 15 SMCRemote Part V Ess Are Pee" },
  { file: "The Craftsman 16 SMCRemote Part VI.md", title: "The Craftsman: 16 SMCRemote Part VI Wham Bam" },
  { file: "The Craftsman 17 SMCRemote Part VII.md", title: "The Craftsman: 17 SMCRemote Part VII Call the Guards" },
  { file: "The Craftsman 18 SMCRemote Part VIII.md", title: "The Craftsman: 18 SMCRemote Part VIII Slow and Steady" },
  { file: "The Craftsman 19 SMCRemote Part IX.md", title: "The Craftsman: 19 SMCRemote Part IX Tolerance" },
  { file: "The Craftsman 20  SMCRemote Part X.md", title: "The Craftsman: 20 SMCRemote Part X Backslide." },
  { file: "The Craftsman 21  SMCRemote Part XI.md", title: "The Craftsman: 21 SMCRemote Part XI Patchwork." },
  { file: "The Craftsman 22  SMCRemote Part XII.md", title: "The Craftsman: 22 SMCRemote Part XII Bug Eye." },
  { file: "The Craftsman 23  SMCRemote Part XIII.md", title: "The Craftsman: 23 SMCRemote Part XIII Raggedy." },
  { file: "The Craftsman 24  Dosimeter Tracking I.md", title: "The Craftsman: 24 Dosage Tracking I OH NO!" },
  { file: "The Craftsman 25  Dosimeter Tracking II.md", title: "The Craftsman: 25 Dosage Tracking II Register Suit" },
  { file: "The Craftsman 26  Dosimeter Tracking III.md", title: "The Craftsman: 26 Dosage Tracking III A Tabled Requirement." },
  { file: "The Craftsman 27  Dosimeter Tracking IV.md", title: "The Craftsman: 27 Dosage Tracking IV Carole's way, or the HighWay." },
  { file: "The Craftsman 28  Dosimeter Tracking V.md", title: "The Craftsman: 28 Dosage Tracking V An Encapsulation Break" },
  { file: "The Craftsman 29  Dosimeter Tracking VI.md", title: "The Craftsman: 29 Dosage Tracking VI Move the Date" },
  { file: "The Craftsman 30  Dosimeter Tracking VII.md", title: "The Craftsman: 30 Dosage Tracking VII The \"Woodshed\"" },
  { file: "The Craftsman 31  Dosimeter Tracking VIII.md", title: "The Craftsman: 31 Dosage Tracking VIII Turn off this Force Field" },
  { file: "The Craftsman 32  Dosimeter Tracking IX.md", title: "The Craftsman: 32 Dosage Tracking IX Indubitably!" },
  { file: "The Craftsman 33  Dosimeter Tracking X.md", title: "The Craftsman: 33 Dosage Tracking X Cleanup on Aisle 10." },
  { file: "The Craftsman 34  Dosimeter Tracking XI.md", title: "The Craftsman: 34 Dosage Tracking XI That's Final." },
  { file: "The Craftsman 35  Dosimeter Tracking XII.md", title: "The Craftsman: 35 Dosage Tracking XII What a day." },
  { file: "The Craftsman 36  Dosimeter Tracking XIII.md", title: "The Craftsman: 36 Dosage Tracking XIII The Color Purple" },
  { file: "The Craftsman 37  Dosimeter Tracking XIV.md", title: "The Craftsman: 37 Dosage Tracking XIV Handling Rejection" },
  { file: "The Craftsman 38  Dosimeter Tracking XV.md", title: "The Craftsman: 38 Dosage Tracking XV Test Independence" },
  { file: "The Craftsman 39  Dosimeter Tracking XVI.md", title: "The Craftsman: 39 Dosage Tracking XVI Test Refactoring" },
  { file: "The Craftsman 40  Dosimeter Tracking XVII.md", title: "The Craftsman: 40 Dosage Tracking XVII Non-trivial trivialities" },
  { file: "The Craftsman 41  Dosimeter Tracking XVIII.md", title: "The Craftsman: 41 Dosage Tracking XVIII Yeah, Sorta." },
  { file: "The Craftsman 42  Dosimeter Tracking XIX.md", title: "The Craftsman: 42 Dosage Tracking XIX Devious Thoughts" },
  { file: "The Craftsman 43  Dosimeter Tracking XX.md", title: "The Craftsman: 43 Dosage Tracking XX Language Lawyers" },
  { file: "The Craftsman 44  Brown Bag I.md", title: "The Craftsman: 44 Brown Bag I Java Generics 2" },
  { file: "The Craftsman 45  Brown Bag II.md", title: "The Craftsman: 45 Brown Bag II Java Generics 2" },
  { file: "The Craftsman 46  Brown Bag III.md", title: "The Craftsman: 46 Brown Bag III Squaring the Circle" },
  { file: "The Craftsman 47 Brown Bag IV.md", title: "The Craftsman: 47 Brown Bag IV Jinx!" },
  { file: "The Craftsman 48 Brown Bag V.md", title: "The Craftsman: 48 Brown Bag V Statenum" },
  { file: "The Craftsman 49 Brown Bag VI.md", title: "The Craftsman: 49 Brown Bag VI Abstract Factory" },
  { file: "The Craftsman 50 Brown Bag VII.md", title: "The Craftsman: 50 Brown Bag VII Ruby" },
  { file: "The Craftsman 51 Brown Bag VIII.md", title: "The Craftsman: 51 Brown Bag VIII Ruby Visitor" },
  { file: "The Craftsman 52 Clean Code C1.md", title: "The Craftsman: 52 Clean Code: C1 Inappropriate Information" },
  { file: "The Craftsman 53 Clean Code C2.md", title: "The Craftsman: 53 Clean Code: C2 Obsolete Comment" },
  { file: "The Craftsman 54 Clean Code C3.md", title: "The Craftsman: 54 Clean Code: C3 Redundant Comment" },
  { file: "The Craftsman 55 Clean Code C4.md", title: "The Craftsman: 55 Clean Code: C4 Poorly Written Comment" },
  { file: "The Craftsman 56 Clean Code C5.md", title: "The Craftsman: 56 Clean Code: C5 Commented Out Code" },
  { file: "The Craftsman 57 Clean Code E1.md", title: "The Craftsman: 57 Clean Code: E1 Multistep Build" },
  { file: "The Craftsman 58 Clean Code E2.md", title: "The Craftsman: 58 Clean Code: E2 One Step Test" },
  { file: "The Craftsman 59 Clean Code F1.md", title: "The Craftsman: 59 Clean Code: F1 Too Many Arguments" },
  { file: "The Craftsman 60 Clean Code F2.md", title: "The Craftsman: 60 Clean Code: F2 Output Arguments" },
  { file: "The Craftsman 61 Clean Code F3.md", title: "The Craftsman: 61 Clean Code: F3 Flag Arguments" },
  { file: "The Craftsman 62 The Dark Path.md", title: "The Craftsman: 62 The Dark Path" },
  { file: "The Craftsman 63 Specifics and Generics.md", title: "The Craftsman: 63 Specifics and Generics" },
];

function articleNumber(article) {
  const match = article.file.match(/The Craftsman\s+(\d+)/);
  return match ? Number.parseInt(match[1], 10) : Number.NaN;
}

function articleHref(file) {
  return `article.html?file=${encodeURIComponent(file)}`;
}
