const HERO_IMAGES = {
  "The Craftsman 01 primes.md": { src: "files/heroes/01-hero.png", alt: "Alphonse nervously presents his first prime-number program to Jerry in a futuristic software lab." },
  "The Craftsman 02 primes.md": { src: "files/heroes/02-hero.png", alt: "Jerry mentors Alphonse through the first refactoring steps at a shared workstation." },
  "The Craftsman 03 primes.md": { src: "files/heroes/03-hero.png", alt: "Alphonse and Jerry perform a careful whole-program read-through in the lab." },
  "The Craftsman 04 Prime Factorizer.md": { src: "files/heroes/04-hero.png", alt: "Hero illustration for The Craftsman: 4, featuring Alphonse, Jerry, Mr. C." },
  "The Craftsman 05 Prime Factorizer.md": { src: "files/heroes/05-hero.png", alt: "Hero illustration for The Craftsman: 5, featuring Alphonse, Jerry." },
  "The Craftsman 06 Socket Service 1.md": { src: "files/heroes/06-hero.png", alt: "Hero illustration for The Craftsman: 6 SocketService 1, featuring Alphonse, Jerry, Mr. C." },
  "The Craftsman 07 Socket Service 2.md": { src: "files/heroes/07-hero.png", alt: "Hero illustration for The Craftsman: 7 SocketService 2, featuring Alphonse, Jerry." },
  "The Craftsman 08 Socket Service 3.md": { src: "files/heroes/08-hero.png", alt: "Hero illustration for The Craftsman: 8 SocketService 3, featuring Alphonse, Jerry." },
  "The Craftsman 09 Socket Service 4.md": { src: "files/heroes/09-hero.png", alt: "Hero illustration for The Craftsman: 9 SocketService 4, featuring Alphonse, Jerry." },
  "The Craftsman 10 Socket Service 5.md": { src: "files/heroes/10-hero.png", alt: "Hero illustration for The Craftsman: 10 SocketService 5 Dangling Threads, featuring Alphonse, Jerry." },
  "The Craftsman 11 SMCRemote Part I.md": { src: "files/heroes/11-hero.png", alt: "Hero illustration for The Craftsman: 11 SMCRemote Part I What's main got to do with it?, featuring Alphonse, Jerry, Mr. C." },
  "The Craftsman 12 SMCRemote Part II.md": { src: "files/heroes/12-hero.png", alt: "Hero illustration for The Craftsman: 12 SMCRemote Part II Three Ugly Lines, featuring Alphonse, Jerry." },
  "The Craftsman 13 SMCRemote Part III.md": { src: "files/heroes/13-hero.png", alt: "Hero illustration for The Craftsman: 13 SMCRemote Part III Objects, featuring Alphonse, Jerry, Jasmine." },
  "The Craftsman 14 SMCRemote Part IV.md": { src: "files/heroes/14-hero.png", alt: "Hero illustration for The Craftsman: 14 SMCRemote Part IV Transactions, featuring Alphonse, Jasmine, Jerry." },
  "The Craftsman 15 SMCRemote Part V.md": { src: "files/heroes/15-hero.png", alt: "Hero illustration for The Craftsman: 15 SMCRemote Part V Ess Are Pee, featuring Alphonse, Jasmine, Jerry." },
  "The Craftsman 16 SMCRemote Part VI.md": { src: "files/heroes/16-hero.png", alt: "Hero illustration for The Craftsman: 16 SMCRemote Part VI Wham Bam, featuring Alphonse, Jasmine, Jerry." },
  "The Craftsman 17 SMCRemote Part VII.md": { src: "files/heroes/17-hero.png", alt: "Hero illustration for The Craftsman: 17 SMCRemote Part VII Call the Guards, featuring Alphonse, Jerry, Jean." },
  "The Craftsman 18 SMCRemote Part VIII.md": { src: "files/heroes/18-hero.png", alt: "Hero illustration for The Craftsman: 18 SMCRemote Part VIII Slow and Steady, featuring Alphonse, Jean, Mr. C." },
  "The Craftsman 19 SMCRemote Part IX.md": { src: "files/heroes/19-hero.png", alt: "Hero illustration for The Craftsman: 19 SMCRemote Part IX Tolerance, featuring Alphonse, Jean, Jasmine." },
  "The Craftsman 20  SMCRemote Part X.md": { src: "files/heroes/20-hero.png", alt: "Hero illustration for The Craftsman: 20 SMCRemote Part X Backslide., featuring Alphonse, Jerry, Jean." },
  "The Craftsman 21  SMCRemote Part XI.md": { src: "files/heroes/21-hero.png", alt: "Hero illustration for The Craftsman: 21 SMCRemote Part XI Patchwork., featuring Alphonse, Jean, Jerry." },
  "The Craftsman 22  SMCRemote Part XII.md": { src: "files/heroes/22-hero.png", alt: "Hero illustration for The Craftsman: 22 SMCRemote Part XII Bug Eye., featuring Alphonse, Jean, Avery." },
  "The Craftsman 23  SMCRemote Part XIII.md": { src: "files/heroes/23-hero.png", alt: "Hero illustration for The Craftsman: 23 SMCRemote Part XIII Raggedy., featuring Alphonse, Avery, Jerry." },
  "The Craftsman 24  Dosimeter Tracking I.md": { src: "files/heroes/24-hero.png", alt: "Hero illustration for The Craftsman: 24 Dosage Tracking I OH NO!, featuring Alphonse, Avery, Jerry." },
  "The Craftsman 25  Dosimeter Tracking II.md": { src: "files/heroes/25-hero.png", alt: "Hero illustration for The Craftsman: 25 Dosage Tracking II Register Suit, featuring Alphonse, Jerry, Carole." },
  "The Craftsman 26  Dosimeter Tracking III.md": { src: "files/heroes/26-hero.png", alt: "Hero illustration for The Craftsman: 26 Dosage Tracking III A Tabled Requirement., featuring Alphonse, Jerry, Avery." },
  "The Craftsman 27  Dosimeter Tracking IV.md": { src: "files/heroes/27-hero.png", alt: "Hero illustration for The Craftsman: 27 Dosage Tracking IV Carole's way, or the HighWay., featuring Alphonse, Jerry, Avery." },
  "The Craftsman 28  Dosimeter Tracking V.md": { src: "files/heroes/28-hero.png", alt: "Hero illustration for The Craftsman: 28 Dosage Tracking V An Encapsulation Break, featuring Alphonse, Jasmine, Avery." },
  "The Craftsman 29  Dosimeter Tracking VI.md": { src: "files/heroes/29-hero.png", alt: "Hero illustration for The Craftsman: 29 Dosage Tracking VI Move the Date, featuring Alphonse, Avery, Jerry." },
  "The Craftsman 30  Dosimeter Tracking VII.md": { src: "files/heroes/30-hero.png", alt: "Hero illustration for The Craftsman: 30 Dosage Tracking VII The \"Woodshed\", featuring Alphonse, Jerry, Avery." },
  "The Craftsman 31  Dosimeter Tracking VIII.md": { src: "files/heroes/31-hero.png", alt: "Hero illustration for The Craftsman: 31 Dosage Tracking VIII Turn off this Force Field, featuring Alphonse, Jerry, Avery." },
  "The Craftsman 32  Dosimeter Tracking IX.md": { src: "files/heroes/32-hero.png", alt: "Hero illustration for The Craftsman: 32 Dosage Tracking IX Indubitably!, featuring Alphonse, Avery, Jerry." },
  "The Craftsman 33  Dosimeter Tracking X.md": { src: "files/heroes/33-hero.png", alt: "Hero illustration for The Craftsman: 33 Dosage Tracking X Cleanup on Aisle 10., featuring Alphonse, Avery, Jerry." },
  "The Craftsman 34  Dosimeter Tracking XI.md": { src: "files/heroes/34-hero.png", alt: "Hero illustration for The Craftsman: 34 Dosage Tracking XI That's Final., featuring Alphonse, Avery, Jerry." },
  "The Craftsman 35  Dosimeter Tracking XII.md": { src: "files/heroes/35-hero.png", alt: "Hero illustration for The Craftsman: 35 Dosage Tracking XII What a day., featuring Alphonse, Avery, Jerry." },
  "The Craftsman 36  Dosimeter Tracking XIII.md": { src: "files/heroes/36-hero.png", alt: "Hero illustration for The Craftsman: 36 Dosage Tracking XIII The Color Purple, featuring Alphonse, Avery, Carole." },
  "The Craftsman 37  Dosimeter Tracking XIV.md": { src: "files/heroes/37-hero.png", alt: "Hero illustration for The Craftsman: 37 Dosage Tracking XIV Handling Rejection, featuring Alphonse, Jasper, Avery." },
  "The Craftsman 38  Dosimeter Tracking XV.md": { src: "files/heroes/38-hero.png", alt: "Hero illustration for The Craftsman: 38 Dosage Tracking XV Test Independence, featuring Alphonse, Jasper, Jean." },
  "The Craftsman 39  Dosimeter Tracking XVI.md": { src: "files/heroes/39-hero.png", alt: "Hero illustration for The Craftsman: 39 Dosage Tracking XVI Test Refactoring, featuring Alphonse, Jasper, Jerry." },
  "The Craftsman 40  Dosimeter Tracking XVII.md": { src: "files/heroes/40-hero.png", alt: "Hero illustration for The Craftsman: 40 Dosage Tracking XVII Non-trivial trivialities, featuring Alphonse, Jasper, Carole." },
  "The Craftsman 41  Dosimeter Tracking XVIII.md": { src: "files/heroes/41-hero.png", alt: "Hero illustration for The Craftsman: 41 Dosage Tracking XVIII Yeah, Sorta., featuring Alphonse, Jasper, Mr. C." },
  "The Craftsman 42  Dosimeter Tracking XIX.md": { src: "files/heroes/42-hero.png", alt: "Hero illustration for The Craftsman: 42 Dosage Tracking XIX Devious Thoughts, featuring Alphonse, Jerry, Jasper." },
  "The Craftsman 43  Dosimeter Tracking XX.md": { src: "files/heroes/43-hero.png", alt: "Hero illustration for The Craftsman: 43 Dosage Tracking XX Language Lawyers, featuring Alphonse, Avery, Jasper." },
  "The Craftsman 44  Brown Bag I.md": { src: "files/heroes/44-hero.png", alt: "Hero illustration for The Craftsman: 44 Brown Bag I Java Generics 2, featuring Adelaide, Avery, Alphonse." },
  "The Craftsman 45  Brown Bag II.md": { src: "files/heroes/45-hero.png", alt: "Hero illustration for The Craftsman: 45 Brown Bag II Java Generics 2, featuring Adelaide, Avery, Alphonse." },
  "The Craftsman 46  Brown Bag III.md": { src: "files/heroes/46-hero.png", alt: "Hero illustration for The Craftsman: 46 Brown Bag III Squaring the Circle, featuring Adelaide, Jerry, Avery." },
  "The Craftsman 47 Brown Bag IV.md": { src: "files/heroes/47-hero.png", alt: "Hero illustration for The Craftsman: 47 Brown Bag IV Jinx!, featuring Adelaide, Avery, Jerry." },
  "The Craftsman 48 Brown Bag V.md": { src: "files/heroes/48-hero.png", alt: "Hero illustration for The Craftsman: 48 Brown Bag V Statenum, featuring Adelaide, Jasmine, Avery." },
  "The Craftsman 49 Brown Bag VI.md": { src: "files/heroes/49-hero.png", alt: "Hero illustration for The Craftsman: 49 Brown Bag VI Abstract Factory, featuring Adelaide, Jasmine, Jean." },
  "The Craftsman 50 Brown Bag VII.md": { src: "files/heroes/50-hero.png", alt: "Hero illustration for The Craftsman: 50 Brown Bag VII Ruby, featuring Adelaide, Jasper, Jasmine." },
  "The Craftsman 51 Brown Bag VIII.md": { src: "files/heroes/51-hero.png", alt: "Hero illustration for The Craftsman: 51 Brown Bag VIII Ruby Visitor, featuring Adelaide, Jerry, Jean." },
  "The Craftsman 52 Clean Code C1.md": { src: "files/heroes/52-hero.png", alt: "Hero illustration for The Craftsman: 52 Clean Code: C1 Inappropriate Information, featuring Mr. C, Jasmine, Adelaide." },
  "The Craftsman 53 Clean Code C2.md": { src: "files/heroes/53-hero.png", alt: "Hero illustration for The Craftsman: 53 Clean Code: C2 Obsolete Comment, featuring Mr. C, Adelaide, Jean." },
  "The Craftsman 54 Clean Code C3.md": { src: "files/heroes/54-hero.png", alt: "Hero illustration for The Craftsman: 54 Clean Code: C3 Redundant Comment, featuring Mr. C, Jerry, Avery." },
  "The Craftsman 55 Clean Code C4.md": { src: "files/heroes/55-hero.png", alt: "Hero illustration for The Craftsman: 55 Clean Code: C4 Poorly Written Comment, featuring Mr. C, Avery, Alphonse." },
  "The Craftsman 56 Clean Code C5.md": { src: "files/heroes/56-hero.png", alt: "Hero illustration for The Craftsman: 56 Clean Code: C5 Commented Out Code, featuring Mr. C, Jean, Alphonse." },
  "The Craftsman 57 Clean Code E1.md": { src: "files/heroes/57-hero.png", alt: "Hero illustration for The Craftsman: 57 Clean Code: E1 Multistep Build, featuring Mr. C, Jasper, Avery." },
  "The Craftsman 58 Clean Code E2.md": { src: "files/heroes/58-hero.png", alt: "Hero illustration for The Craftsman: 58 Clean Code: E2 One Step Test, featuring Mr. C, Jean, Jasmine." },
  "The Craftsman 59 Clean Code F1.md": { src: "files/heroes/59-hero.png", alt: "Hero illustration for The Craftsman: 59 Clean Code: F1 Too Many Arguments, featuring Mr. C, Jasmine, Jerry." },
  "The Craftsman 60 Clean Code F2.md": { src: "files/heroes/60-hero.png", alt: "Hero illustration for The Craftsman: 60 Clean Code: F2 Output Arguments, featuring Mr. C, Jasmine, Jerry." },
  "The Craftsman 61 Clean Code F3.md": { src: "files/heroes/61-hero.png", alt: "Hero illustration for The Craftsman: 61 Clean Code: F3 Flag Arguments, featuring Mr. C, Jerry, Alphonse." },
  "The Craftsman 62 The Dark Path.md": { src: "files/heroes/62-hero.png", alt: "Hero illustration for The Craftsman: 62 The Dark Path, featuring Mr. C, Jerry, Alphonse." },
  "The Craftsman 63 Specifics and Generics.md": { src: "files/heroes/63-hero.png", alt: "Hero illustration for The Craftsman: 63 Specifics and Generics, featuring Mr. C, Avery, Alphonse." },
};
